version: '3.8'

services:
  my-app-frontend-dev:
    image: my-app-frontend-dev
    volumes:
      - ./frontend:/usr/src/app
    container_name: my-app-frontend-dev
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile

  my-app-backend-dev:
    image: my-app-backend-dev
    volumes:
      - ./backend:/usr/src/app
    container_name: my-app-backend-dev
    ports:
      - 3001:3001
    environment:
      MONGODB_URI: mongodb://the_username:the_password@mongo:27017/the_database
    build:
      context: ./backend
      dockerfile: dev.Dockerfile

  mongo:
    image: mongo
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 3456:27017
    container_name: my-app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
