version: '3.8'

services:
  todo-frontend:
    image: todo-frontend
    container_name: todo-frontend
    environment:
      REACT_APP_BACKEND_URL: api

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - todo-frontend

  todo-backend:
    image: todo-backend
    container_name: todo-backend
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379

  mongo:
    image: mongo
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 3456:27017
    container_name: todo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

  redis:
    image: redis
    volumes:
      - ./todo-backend/redis_data:/data
    ports:
      - 6379:6379
    container_name: todo-redis
    command: [ 'redis-server', '--appendonly', 'yes' ]
